server:
   port: 8082
# 数据库连接
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/hgpad?serverTimezone=UTC
      username: cwj
      password: 123456
      #driver-class-name: com.mysql.cj.jdbc.Driver
   
   jpa:
      properties:
         hibernate:
            hbm2ddl:
               auto: update
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
      hibernate:
         naming:
            implicit-strategy: com.erp.hgpad.config.MyImplicitNamingStrategyJpaCompliant
            
   thymeleaf:
      mode: LEGACYHTML5
      cache: false

#本地文件路径
myConfig:
   basePath: F:/hgpad/
   picWidth: 600
   picWidth2: 1920
   picWidth3: 960
   nowUrl: http://localhost:${server.port}


